[[collection]]
type = "card_simple"
title = "atuin"
link = "https://atuin.sh/"
content = "The magical shell history tool loved by developers worldwide. Sync your commands across machines, search everything instantly, and keep your data encrypted. Open source."

[[collection]]
type = "card_simple"
title = "bat"
link = "https://github.com/sharkdp/bat"
content = "A cat(1) clone with syntax highlighting and Git integration."

[[collection]]
type = "card_simple"
title = "bottom"
link = "https://github.com/ClementTsang/bottom"
content = "A customizable cross-platform graphical process/system monitor for the terminal."

[[collection]]
type = "card_simple"
title = "difftastic"
link = "https://difftastic.wilfred.me.uk/"
content = "Difftastic is a CLI diff tool that compares files based on their syntax, not line-by-line. Difftastic produces accurate diffs that are easier for humans to read."

[[collection]]
type = "card_simple"
title = "direnv"
link = "https://direnv.net/"
content = "direnv is an extension for your shell. It augments existing shells with a new feature that can load and unload environment variables depending on the current directory."

[[collection]]
type = "card_simple"
title = "duckdb"
link = "https://duckdb.org/"
content = "DuckDB is an in-process analytical SQL engine."

[[collection]]
type = "card_simple"
title = "jq"
link = "https://jqlang.org/"
content = "jq is like sed for JSON data - you can use it to slice and filter and map and transform structured data with the same ease that sed, awk, grep and friends let you play with text."

[[collection]]
type = "card_simple"
title = "k9s"
link = "https://k9scli.io/"
content = "K9s is a terminal based UI to interact with your Kubernetes clusters. The aim of this project is to make it easier to navigate, observe and manage your deployed applications in the wild. K9s continually watches Kubernetes for changes and offers subsequent commands to interact with your observed resources."

[[collection]]
type = "card_simple"
title = "mpv"
link = "https://github.com/mpv-player/mpv"
content = "mpv is a free (as in freedom) media player for the command line. It supports a wide variety of media file formats, audio and video codecs, and subtitle types."

[[collection]]
type = "card_simple"
title = "neovim"
link = "https://neovim.io/"
content = "I use vim, btw."

[[collection]]
type = "card_simple"
title = "tmux"
link = "https://github.com/tmux/tmux"
content = "tmux is a terminal multiplexer: it enables a number of terminals to be created, accessed, and controlled from a single screen. tmux may be detached from a screen and continue running in the background, then later reattached."

[[collection]]
type = "card_simple"
title = "tree"
link = "https://peteretelej.github.io/tree/"
content = "tree is an open-source tree command-line application that recursively displays the directory structure of a given path in a tree-like format, inspired by the Unix tree command."

[[collection]]
type = "card_simple"
title = "tree"
link = "https://peteretelej.github.io/tree/"
content = "tree is an open-source tree command-line application that recursively displays the directory structure of a given path in a tree-like format, inspired by the Unix tree command."
